; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32@6.5.0
framework = arduino
lib_extra_dirs = D:\Arduino\libraries
lib_deps = 
	D:\Arduino\libraries\bsec2
	D:\Arduino\libraries\bsec_v3-3-0-0
	D:\Arduino\libraries.def\bsec_v3-3-0-0
	D:\Arduino\libraries.def\BME68x_Sensor_library
	https://github.com/DFRobot/DFRobot_BMM350
	adafruit/Adafruit LSM6DS@^4.7.4
	adafruit/Adafruit LIS3MDL@^1.2.5
	sparkfun/SparkFun AS7343 Arduino Library
	adafruit/Adafruit TCS34725@^1.4.4
	adafruit/Adafruit OPT4048@^1.0.2
	adafruit/Adafruit MLX90640@^1.1.2
	https://github.com/silasmariusz/I2C_Addr_LS.git

board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
upload_port = COM3
build_flags = 
	-I "D:/Arduino/libraries/bsec2/src"
	-I "D:/Arduino/libraries/bsec_v3-3-0-0"
	-I "D:/Arduino/libraries.def/bsec_v3-3-0-0"
	-I "D:/Arduino/libraries/Renesas-ZMOD4510-NO2_O3-Firmware/src"
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-mfix-esp32-psram-cache-issue
	"-LD:/Arduino/libraries/Renesas-ZMOD4510-NO2_O3-Firmware/lib/Espressif ESP/esp32s3/xtensa-esp32s3-elf-gcc"
	-Wl,--start-group
	-l_no2_o3
	-l_zmod4xxx_cleaning
	-Wl,--end-group
lib_ldf_mode = chain
board = seeed_xiao_esp32s3
