[env:esp32-s3-devkitc-1]
platform = espressif32@6.5.0
framework = arduino
lib_extra_dirs = D:\Arduino\libraries
lib_deps =
    https://github.com/silasmariusz/I2C_Addr_LS.git
    paolop74/extEEPROM
    sparkfun/SparkFun BMV080 Arduino Library
    stm32duino/STM32duino ILPS22QS
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit SHT4x Library
    adafruit/Adafruit BMP5xx Library
    Sensirion/Sensirion I2C SGP41
    Sensirion/Sensirion I2C SCD4x
    Sensirion/Sensirion Gas Index Algorithm
    ArduinoJson
    ArduinoOTA
    ESPmDNS
    WebServer
    PubSubClient
    dfrobot/DFRobot_AS3935

board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
upload_port = COM11
upload_protocol = esptool
monitor_port = COM11

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

build_flags =
    -I "D:/Arduino/libraries/bsec_v3-3-0-0/release_bin/IAQ/inc"
    -I "D:/Arduino/libraries/bsec_v3-3-0-0/examples/BME690/src/bme69x"
    -I "D:/Arduino/libraries/Renesas-ZMOD4510-NO2_O3-Firmware/src"
    -I "D:/Arduino/libraries/bmv080-sdk-v11-2-0/api/inc"
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -mfix-esp32-psram-cache-issue
    "-LD:/Arduino/libraries/bsec_v3-3-0-0/release_bin/Sel_IAQ/bin/esp32/esp32s3"
    "-LD:/Arduino/libraries/Renesas-ZMOD4510-NO2_O3-Firmware/lib/Espressif ESP/esp32s3/xtensa-esp32s3-elf-gcc"
    "-LD:/Arduino/libraries/bmv080-sdk-v11-2-0/api/lib/xtensa_esp32s3/xtensa_esp32s3_elf_gcc/release"
    -Wl,--start-group
    -lalgobsec
    -l_no2_o3
    -l_zmod4xxx_cleaning
    -l_bmv080
    -l_postProcessor
    -Wl,--end-group

lib_ldf_mode = chain
board = esp32-s3-devkitc-1
